# Copyright Planetmint GmbH and Planetmint contributors
# SPDX-License-Identifier: (Apache-2.0 AND CC-BY-4.0)
# Code is Apache-2.0 and docs are CC-BY-4.0

sudo: required
os: linux
dist: focal
services:
  - docker

language: python
cache: pip
python:
  - 3.9

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.25.0
  jobs:
    - TOXENV=py39
    - TOXENV=flake8
    - TOXENV=docs

jobs:
  fast_finish: true
  include:
    - python: 3.9
      env: TOXENV=flake8
    - python: 3.9
      env: TOXENV=docs
    - python: 3.9
      env: TOXENV=py39

before_install:
  - sudo .ci/travis-before-install.sh

install:
  - .ci/travis-install.sh

before_script:
  - .ci/travis-before-script.sh

script: .ci/travis_script.sh

after_success:
  - .ci/travis-after-success.sh
